### ISSUE TITLE
[MAP]: Figa-MaxUnit1400

### ISSUE THREAD

**Issue by rbabbit** [Warzone2100/map-submission#115]
### Upload Map

[6c-Figa-MaxUnit1400.zip](https://github.com/user-attachments/files/16566196/6c-Figa-MaxUnit1400.zip)

### Authorship

Other: This map was made by someone else

**Comment by KJeff01** [comment]
An interesting idea but map-mods aren't supported as the script folder will get stripped if merged. There are also a few oil derricks placed in bad positions leading to error messages.
