### ISSUE TITLE
[MAP]: Roadside

### ISSUE THREAD

**Issue by Xlutch** [Warzone2100/map-submission#125]
### Upload Map

[4c-Roadside.wz.zip](https://github.com/user-attachments/files/17355360/4c-Roadside.wz.zip)

### Authorship

Mine: I am the author of this map

### Map Description (optional)

```text
I created Roadside as one of my very first maps. It wouldn't be the last though!!!
I learned alot from this very map, and I have made 2 others, with another one being
a wip!
```

### Notes for Reviewers (optional)

Hello! If you are writing anything down here, I'll try my best to look and reply!

[Author Note.txt](https://github.com/user-attachments/files/17355361/Author.Note.txt)

**Comment by Xlutch** [comment]
Yes, I made an account for Warzone 2100. Yes, this'll be my only thing I do on this account

**Comment by vaut** [comment]
Please correct the attached archive with the map.
Instructions on how to properly prepare the archive:
https://github.com/Warzone2100/map-submission/blob/main/docs/submit_map.md

**Comment by Xlutch** [comment]
> Please correct the attached archive with the map. Instructions on how to properly prepare the archive: https://github.com/Warzone2100/map-submission/blob/main/docs/submit_map.md

Oh! I see. One sec...

**Comment by Xlutch** [comment]
> Please correct the attached archive with the map. Instructions on how to properly prepare the archive: https://github.com/Warzone2100/map-submission/blob/main/docs/submit_map.md

Edited! is this better?

**Comment by Xlutch** [comment]
> /replace validation

?

**Comment by Xlutch** [comment]
wha- hah?

**Comment by Xlutch** [comment]
i see moderator instructions, I try approve

**Comment by Xlutch** [comment]
...
darniddily doo

**Comment by Xlutch** [comment]
> /replace validation

Hello! I have made a fixed version of the map just now! Check it when you can, please?
