### ISSUE TITLE
[MAP]:ok, Now, It's Roadside

### ISSUE THREAD

**Issue by Xlutch** [Warzone2100/map-submission#127]
### Upload Map

[4c-Roadside_Fixed.1.wz.zip](https://github.com/user-attachments/files/17424738/4c-Roadside_Fixed.1.wz.zip)
^^This guy is here, I guess^^
### Authorship

Mine: I am the author of this map

### Map Description (optional)

```text
Gawd, third instance of this map. This is THE fixed version. Enjoy!
```

### Notes for Reviewers (optional)

credit smithblackery alongside me, please.

**Comment by past-due** [comment]
@Xlutch Please open a new map submission, and attach *only* the map .wz file (renamed with a .zip extension) in the “Upload Map” section.

**Comment by Xlutch** [comment]
> @Xlutch Please open a new map submission, and attach _only_ the map .wz file (renamed with a .zip extension) in the “Upload Map” section.

k
