### ISSUE TITLE
[MAP]: RoadsideFixdDot2.wz.zip

### ISSUE THREAD

**Issue by Xlutch** [Warzone2100/map-submission#129]
### Upload Map

[4c-RoadsideFixdDot2.wz.zip](https://github.com/user-attachments/files/17426091/4c-RoadsideFixdDot2.wz.zip)

LITERALLY the final one
I hope

### Authorship

Mine: I am the author of this map

### Map Description (optional)

```text
wee
```

### Notes for Reviewers (optional)

woo

**Comment by KJeff01** [comment]
An interesting map. The one problem I saw is that the pre-placed artifacts can't be picked up.

**Comment by Xlutch** [comment]
> An interesting map. The one problem I saw is that the pre-placed artifacts can't be picked up.

pre-placed artifacts?

**Comment by Xlutch** [comment]
> An interesting map. The one problem I saw is that the pre-placed artifacts can't be picked up.

wait, I see now. I just needed some crates lol
