### ISSUE TITLE
[MAP]: Concrete Jungle

### ISSUE THREAD

**Issue by Mtlhead7** [Warzone2100/map-submission#134]
### Upload Map

[10c-Concrete_Jungle.zip](https://github.com/user-attachments/files/17466976/10c-Concrete_Jungle.zip)

### Authorship

Mine: I am the author of this map

### Map Description (optional)

```text
10 Player Skirmish
```

**Comment by KJeff01** [comment]
Unfortunately just one more thing: positions 9 and 4 have incorrectly rotated factories compared to the rest of the players on their side. Other than that it all looks good to me. :+1:

**Comment by Mtlhead7** [comment]
Fixed and uploaded to a new issue.
Don

**Comment by Mtlhead7** [comment]
Ok, please delete issue #135.  I uploaded the wrong file.

Issue #136 is the correct and fixed version.  Sorry for the confusion!
It's been Monday all day.
Don
