### ISSUE TITLE
[MAP]: 2c-AmigosMap1v1FB

### ISSUE THREAD

**Issue by Enricopre** [Warzone2100/map-submission#21]
### Upload Map

[2c-AmigosMap1v1FB.zip](https://github.com/Warzone2100/map-submission/files/12388111/2c-AmigosMap1v1FB.zip)

### Authorship

Mine: I am the author of this map

### Map Description (optional)

```text
Map to play 1v1 with a new design and a spacious battlefield
```

**Comment by vaut** [comment]
Another empty board.
