### ISSUE TITLE
[MAP]: Ng-Temple

### ISSUE THREAD

**Issue by Nergal-wz** [Warzone2100/map-submission#30]
### Upload Map

[6c-Ng-Temple.wz.zip](https://github.com/Warzone2100/map-submission/files/13055232/6c-Ng-Temple.wz.zip)

### Authorship

Other: This map was made by someone else

### Map Description (optional)

```text
Low oils 3v3
```

**Comment by KJeff01** [comment]
There is a small issue on all the mounds with water in them.

![water](https://github.com/Warzone2100/map-submission/assets/22485442/de399d1f-5241-41a1-8d3e-ed8574586c14)

**Comment by Nergal-wz** [comment]
![ng-templeissue](https://github.com/Warzone2100/map-submission/assets/148555879/611314c2-734e-4a99-ac6d-4e0936437c6f)
This is how it appears in flame; i just had the same issue in other maps, often with waterfalls; i tried to fix changing textures, but it didn't work; i think i'll have to make it flat.
