### ISSUE TITLE
[MAP]: Ng-Cymatic

### ISSUE THREAD

**Issue by Nergal-wz** [Warzone2100/map-submission#41]
### Upload Map

[8c-Ng-Cymatic.wz.zip](https://github.com/Warzone2100/map-submission/files/13055679/8c-Ng-Cymatic.wz.zip)

### Authorship

Mine: I am the author of this map

### Map Description (optional)

```text
Low oils map for FFA games; it could be played also 4v4 or 2v2v2v2
```

**Comment by KJeff01** [comment]
Map is good. The warnings are just due to always starting with HQ at most (like the built-in maps 4/8p-Cockate).
