### ISSUE TITLE
[MAP]: Ng-ThisMapSucks

### ISSUE THREAD

**Issue by Nergal-wz** [Warzone2100/map-submission#52]
### Upload Map

[8c-Ng-ThisMapSucks.wz.zip](https://github.com/Warzone2100/map-submission/files/13055929/8c-Ng-ThisMapSucks.wz.zip)

### Authorship

Mine: I am the author of this map

### Map Description (optional)

```text
4v4 medium oils map
```

**Comment by vaut** [comment]
Too protected positions.
Playing with ground vehicles is not possible. Everything will come down to art and work. And it will only end when one of the teams gets tired of playing.

You can add dynamics by moving some of the oil to the central part.
