### ISSUE TITLE
[MAP]: Ng-DefCon

### ISSUE THREAD

**Issue by Nergal-wz** [Warzone2100/map-submission#59]
### Upload Map

[10c-Ng-DefCon.wz.zip](https://github.com/Warzone2100/map-submission/files/13056081/10c-Ng-DefCon.wz.zip)

### Authorship

Mine: I am the author of this map

### Map Description (optional)

```text
High oils 5v5 for long games
```

**Comment by KJeff01** [comment]
Potentially infinite meatgrinder games.
