### ISSUE TITLE
[MAP]: Ng-UrbaNTW

### ISSUE THREAD

**Issue by Nergal-wz** [Warzone2100/map-submission#67]
### Upload Map

[10c-Ng-UrbaNTW.wz.zip](https://github.com/Warzone2100/map-submission/files/13056270/10c-Ng-UrbaNTW.wz.zip)

### Authorship

Mine: I am the author of this map

### Map Description (optional)

```text
NTW in urban scenario
```

**Comment by KJeff01** [comment]
Truly stunning. All NTW map makers could learn a thing or two about map design with this one.
