### ISSUE TITLE
[MAP]: Ng-WarritRiver

### ISSUE THREAD

**Issue by Nergal-wz** [Warzone2100/map-submission#68]
### Upload Map

[10c-Ng-WarritRiver.wz.zip](https://github.com/Warzone2100/map-submission/files/13056285/10c-Ng-WarritRiver.wz.zip)

### Authorship

Mine: I am the author of this map

### Map Description (optional)

```text
5v5 map with unbalanced slots
```

**Comment by KJeff01** [comment]
![err](https://github.com/Warzone2100/map-submission/assets/22485442/807b6270-753b-4d3e-88b6-8d1a51b086a7)

I feel that you intended for the thinner paths on the plateau around the lakes to be useful, as there are some seemingly large openings that a tank could fit through. Might want to check that out. Despite the screenshot, those debug spawned trucks can't move anywhere as the paths aren't wide enough or maybe they are blocked by cliffs.
