### ISSUE TITLE
[MAP]: NTW_4v4_Edit

### ISSUE THREAD

**Issue by Rawvy** [Warzone2100/map-submission#81]
### Upload Map

[8c-NTW_4v4_Edit.wz.zip](https://github.com/Warzone2100/map-submission/files/13974941/8c-NTW_4v4_Edit.wz.zip)

### Authorship

Mine: I am the author of this map

### Map Description (optional)

```text
Edit of a NTW map to improve scavs and make fights more interesting. Ledge now is accessible via middle but is heavily reinforced. Loads of AA and scavs get tacked T3 units so best avoid early provocations.
```

**Comment by KJeff01** [comment]
Only moderators can approve. :wink: 

There are scavenger defenses too close to the edge of the map generating errors. They are Whirlwind and Avenger sites from what I can tell. Typically these structures would be about 2 tiles away from a map edge.

```
 [loadWzMapStructure:6159] Structure P0-AASite-SAM1, coord too near the edge of the map
 [loadWzMapStructure:6159] Structure AASite-QuadRotMg, coord too near the edge of the map
 [loadWzMapStructure:6159] Structure P0-AASite-SAM1, coord too near the edge of the map
```

**Comment by KJeff01** [comment]
You may resubmit this map in a new issue after correcting the errors with the above mentioned maps.
