### ISSUE TITLE
[MAP]: Mikes Island

### ISSUE THREAD

**Issue by hcindus** [Warzone2100/map-submission#94]
### Upload Map

This was a map I saw online and recreated it for Warzone 2100.  I call it Mikes Island.
[map-preview (1).zip](https://github.com/Warzone2100/map-submission/files/14389513/map-preview.1.zip)

### Authorship

Mine: I am the author of this map

### Map Description (optional)

```text
Mike's Island is a Final Fantasy IV map - for Warzone 2100 minus the monsters.
```

**Comment by KJeff01** [comment]
This is just a picture of a map...
